export const itens = function (id: number) {
  //https://api.steampowered.com/IEconDOTA2_205790/GetGameItems/v1/?key=**&language=en_us&format=JSON
  const list = [
    {
      id: 1,
      name: "blink",
      cost: 2250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 600,
      name: "overwhelming_blink",
      cost: 6800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 603,
      name: "swift_blink",
      cost: 6800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 604,
      name: "arcane_blink",
      cost: 6800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 606,
      name: "recipe_arcane_blink",
      cost: 1750,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 607,
      name: "recipe_swift_blink",
      cost: 1750,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 608,
      name: "recipe_overwhelming_blink",
      cost: 1750,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 2,
      name: "blades_of_attack",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 3,
      name: "broadsword",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 4,
      name: "chainmail",
      cost: 550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 5,
      name: "claymore",
      cost: 1350,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 6,
      name: "helm_of_iron_will",
      cost: 975,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 7,
      name: "javelin",
      cost: 1100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 8,
      name: "mithril_hammer",
      cost: 1600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 9,
      name: "platemail",
      cost: 1400,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 10,
      name: "quarterstaff",
      cost: 875,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 11,
      name: "quelling_blade",
      cost: 100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 237,
      name: "faerie_fire",
      cost: 70,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 265,
      name: "infused_raindrop",
      cost: 225,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 244,
      name: "wind_lace",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 12,
      name: "ring_of_protection",
      cost: 175,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 182,
      name: "stout_shield",
      cost: 100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 246,
      name: "recipe_moon_shard",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 247,
      name: "moon_shard",
      cost: 4000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 13,
      name: "gauntlets",
      cost: 140,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 14,
      name: "slippers",
      cost: 140,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 15,
      name: "mantle",
      cost: 140,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 16,
      name: "branches",
      cost: 50,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 17,
      name: "belt_of_strength",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 18,
      name: "boots_of_elves",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 19,
      name: "robe",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 20,
      name: "circlet",
      cost: 155,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 261,
      name: "crown",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 21,
      name: "ogre_axe",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 22,
      name: "blade_of_alacrity",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 23,
      name: "staff_of_wizardry",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 24,
      name: "ultimate_orb",
      cost: 2050,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 25,
      name: "gloves",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 485,
      name: "blitz_knuckles",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 26,
      name: "lifesteal",
      cost: 900,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 473,
      name: "voodoo_mask",
      cost: 700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 27,
      name: "ring_of_regen",
      cost: 175,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 279,
      name: "ring_of_tarrasque",
      cost: 650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 28,
      name: "sobi_mask",
      cost: 175,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 29,
      name: "boots",
      cost: 500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 30,
      name: "gem",
      cost: 900,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 31,
      name: "cloak",
      cost: 500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 32,
      name: "talisman_of_evasion",
      cost: 1300,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 33,
      name: "cheese",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 34,
      name: "magic_stick",
      cost: 200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 35,
      name: "recipe_magic_wand",
      cost: 150,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 36,
      name: "magic_wand",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 37,
      name: "ghost",
      cost: 1500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 38,
      name: "clarity",
      cost: 50,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 216,
      name: "enchanted_mango",
      cost: 65,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 39,
      name: "flask",
      cost: 100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 40,
      name: "dust",
      cost: 80,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 41,
      name: "bottle",
      cost: 675,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 42,
      name: "ward_observer",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 43,
      name: "ward_sentry",
      cost: 50,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 217,
      name: "recipe_ward_dispenser",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 218,
      name: "ward_dispenser",
      cost: 50,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 44,
      name: "tango",
      cost: 90,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 241,
      name: "tango_single",
      cost: 30,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 45,
      name: "courier",
      cost: 50,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 286,
      name: "flying_courier",
      cost: 100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 46,
      name: "tpscroll",
      cost: 100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 47,
      name: "recipe_travel_boots",
      cost: 2000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 219,
      name: "recipe_travel_boots_2",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 48,
      name: "travel_boots",
      cost: 2500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 220,
      name: "travel_boots_2",
      cost: 4500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 49,
      name: "recipe_phase_boots",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 50,
      name: "phase_boots",
      cost: 1500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 51,
      name: "demon_edge",
      cost: 2200,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 52,
      name: "eagle",
      cost: 2800,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 53,
      name: "reaver",
      cost: 2800,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 54,
      name: "relic",
      cost: 3750,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 55,
      name: "hyperstone",
      cost: 2000,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 56,
      name: "ring_of_health",
      cost: 825,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 57,
      name: "void_stone",
      cost: 825,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 58,
      name: "mystic_staff",
      cost: 2800,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 59,
      name: "energy_booster",
      cost: 800,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 60,
      name: "point_booster",
      cost: 1200,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 61,
      name: "vitality_booster",
      cost: 1000,
      secret_shop: 1,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 593,
      name: "fluffy_hat",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 62,
      name: "recipe_power_treads",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 63,
      name: "power_treads",
      cost: 1400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 653,
      name: "recipe_grandmasters_glaive",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 655,
      name: "grandmasters_glaive",
      cost: 5000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 64,
      name: "recipe_hand_of_midas",
      cost: 1750,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 65,
      name: "hand_of_midas",
      cost: 2200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 66,
      name: "recipe_oblivion_staff",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 67,
      name: "oblivion_staff",
      cost: 1500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 533,
      name: "recipe_witch_blade",
      cost: 600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 534,
      name: "witch_blade",
      cost: 2600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 68,
      name: "recipe_pers",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 69,
      name: "pers",
      cost: 1650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 70,
      name: "recipe_poor_mans_shield",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 71,
      name: "poor_mans_shield",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 731,
      name: "satchel",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 72,
      name: "recipe_bracer",
      cost: 210,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 73,
      name: "bracer",
      cost: 505,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 74,
      name: "recipe_wraith_band",
      cost: 210,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 75,
      name: "wraith_band",
      cost: 505,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 76,
      name: "recipe_null_talisman",
      cost: 210,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 77,
      name: "null_talisman",
      cost: 505,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 78,
      name: "recipe_mekansm",
      cost: 800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 79,
      name: "mekansm",
      cost: 1775,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 80,
      name: "recipe_vladmir",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 81,
      name: "vladmir",
      cost: 2450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 907,
      name: "recipe_wraith_pact",
      cost: 400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 908,
      name: "wraith_pact",
      cost: 4050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 85,
      name: "recipe_buckler",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 86,
      name: "buckler",
      cost: 425,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 87,
      name: "recipe_ring_of_basilius",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 88,
      name: "ring_of_basilius",
      cost: 425,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 268,
      name: "recipe_holy_locket",
      cost: 475,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 269,
      name: "holy_locket",
      cost: 2400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 89,
      name: "recipe_pipe",
      cost: 1550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 90,
      name: "pipe",
      cost: 3475,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 91,
      name: "recipe_urn_of_shadows",
      cost: 375,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 92,
      name: "urn_of_shadows",
      cost: 880,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 93,
      name: "recipe_headdress",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 94,
      name: "headdress",
      cost: 425,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 95,
      name: "recipe_sheepstick",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 96,
      name: "sheepstick",
      cost: 5675,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 97,
      name: "recipe_orchid",
      cost: 300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 98,
      name: "orchid",
      cost: 3475,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 245,
      name: "recipe_bloodthorn",
      cost: 925,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 250,
      name: "bloodthorn",
      cost: 6800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 251,
      name: "recipe_echo_sabre",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 252,
      name: "echo_sabre",
      cost: 2500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 99,
      name: "recipe_cyclone",
      cost: 650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 100,
      name: "cyclone",
      cost: 2725,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 612,
      name: "recipe_wind_waker",
      cost: 1300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 610,
      name: "wind_waker",
      cost: 6825,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 233,
      name: "recipe_aether_lens",
      cost: 650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 232,
      name: "aether_lens",
      cost: 2275,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 101,
      name: "recipe_force_staff",
      cost: 950,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 102,
      name: "force_staff",
      cost: 2200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 262,
      name: "recipe_hurricane_pike",
      cost: 350,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 263,
      name: "hurricane_pike",
      cost: 4450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 103,
      name: "recipe_dagon",
      cost: 1250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 197,
      name: "recipe_dagon_2",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 198,
      name: "recipe_dagon_3",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 199,
      name: "recipe_dagon_4",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 200,
      name: "recipe_dagon_5",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 104,
      name: "dagon",
      cost: 2700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 201,
      name: "dagon_2",
      cost: 3950,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 202,
      name: "dagon_3",
      cost: 5200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 203,
      name: "dagon_4",
      cost: 6450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 204,
      name: "dagon_5",
      cost: 7700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 105,
      name: "recipe_necronomicon",
      cost: 1250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 191,
      name: "recipe_necronomicon_2",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 192,
      name: "recipe_necronomicon_3",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 106,
      name: "necronomicon",
      cost: 2050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 193,
      name: "necronomicon_2",
      cost: 3300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 194,
      name: "necronomicon_3",
      cost: 4550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 107,
      name: "recipe_ultimate_scepter",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 108,
      name: "ultimate_scepter",
      cost: 4200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 270,
      name: "recipe_ultimate_scepter_2",
      cost: 1600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 271,
      name: "ultimate_scepter_2",
      cost: 5800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 727,
      name: "ultimate_scepter_roshan",
      cost: 5800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 609,
      name: "aghanims_shard",
      cost: 1400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 725,
      name: "aghanims_shard_roshan",
      cost: 1400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 109,
      name: "recipe_refresher",
      cost: 1700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 110,
      name: "refresher",
      cost: 5000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 111,
      name: "recipe_assault",
      cost: 1300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 112,
      name: "assault",
      cost: 5125,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 113,
      name: "recipe_heart",
      cost: 1200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 114,
      name: "heart",
      cost: 5000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 115,
      name: "recipe_black_king_bar",
      cost: 1450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 116,
      name: "black_king_bar",
      cost: 4050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 117,
      name: "aegis",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 118,
      name: "recipe_shivas_guard",
      cost: 650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 119,
      name: "shivas_guard",
      cost: 4850,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 120,
      name: "recipe_bloodstone",
      cost: 700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 121,
      name: "bloodstone",
      cost: 4400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 122,
      name: "recipe_sphere",
      cost: 900,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 123,
      name: "sphere",
      cost: 4600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 221,
      name: "recipe_lotus_orb",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 226,
      name: "lotus_orb",
      cost: 3850,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 222,
      name: "recipe_meteor_hammer",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 223,
      name: "meteor_hammer",
      cost: 2350,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 224,
      name: "recipe_nullifier",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 225,
      name: "nullifier",
      cost: 4725,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 255,
      name: "recipe_aeon_disk",
      cost: 1200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 256,
      name: "aeon_disk",
      cost: 3000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 258,
      name: "recipe_kaya",
      cost: 600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 259,
      name: "kaya",
      cost: 2050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 369,
      name: "trident",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 276,
      name: "combo_breaker",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 260,
      name: "refresher_shard",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 266,
      name: "recipe_spirit_vessel",
      cost: 1100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 267,
      name: "spirit_vessel",
      cost: 2980,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 124,
      name: "recipe_vanguard",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 125,
      name: "vanguard",
      cost: 1825,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 243,
      name: "recipe_crimson_guard",
      cost: 800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 242,
      name: "crimson_guard",
      cost: 3600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 126,
      name: "recipe_blade_mail",
      cost: 550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 127,
      name: "blade_mail",
      cost: 2100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 128,
      name: "recipe_soul_booster",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 129,
      name: "soul_booster",
      cost: 3000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 130,
      name: "recipe_hood_of_defiance",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 131,
      name: "hood_of_defiance",
      cost: 1500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 691,
      name: "recipe_eternal_shroud",
      cost: 1100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 692,
      name: "eternal_shroud",
      cost: 3300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 132,
      name: "recipe_rapier",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 133,
      name: "rapier",
      cost: 5950,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 134,
      name: "recipe_monkey_king_bar",
      cost: 675,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 135,
      name: "monkey_king_bar",
      cost: 4975,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 136,
      name: "recipe_radiance",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 137,
      name: "radiance",
      cost: 5050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 138,
      name: "recipe_butterfly",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 139,
      name: "butterfly",
      cost: 4975,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 140,
      name: "recipe_greater_crit",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 141,
      name: "greater_crit",
      cost: 5150,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 142,
      name: "recipe_basher",
      cost: 825,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 143,
      name: "basher",
      cost: 2875,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 144,
      name: "recipe_bfury",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 145,
      name: "bfury",
      cost: 4100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 146,
      name: "recipe_manta",
      cost: 500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 147,
      name: "manta",
      cost: 4600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 148,
      name: "recipe_lesser_crit",
      cost: 500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 149,
      name: "lesser_crit",
      cost: 1950,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 234,
      name: "recipe_dragon_lance",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 236,
      name: "dragon_lance",
      cost: 1900,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 150,
      name: "recipe_armlet",
      cost: 625,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 151,
      name: "armlet",
      cost: 2500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 183,
      name: "recipe_invis_sword",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 152,
      name: "invis_sword",
      cost: 3000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 248,
      name: "recipe_silver_edge",
      cost: 500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 249,
      name: "silver_edge",
      cost: 5450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 153,
      name: "recipe_sange_and_yasha",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 154,
      name: "sange_and_yasha",
      cost: 4100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 272,
      name: "recipe_kaya_and_sange",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 273,
      name: "kaya_and_sange",
      cost: 4100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 274,
      name: "recipe_yasha_and_kaya",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 277,
      name: "yasha_and_kaya",
      cost: 4100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 155,
      name: "recipe_satanic",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 156,
      name: "satanic",
      cost: 5050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 157,
      name: "recipe_mjollnir",
      cost: 900,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 158,
      name: "mjollnir",
      cost: 5600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 159,
      name: "recipe_skadi",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 160,
      name: "skadi",
      cost: 5300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 161,
      name: "recipe_sange",
      cost: 600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 162,
      name: "sange",
      cost: 2050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 163,
      name: "recipe_helm_of_the_dominator",
      cost: 975,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 164,
      name: "helm_of_the_dominator",
      cost: 2400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 633,
      name: "recipe_helm_of_the_overlord",
      cost: 1325,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 635,
      name: "helm_of_the_overlord",
      cost: 6175,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 165,
      name: "recipe_maelstrom",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 166,
      name: "maelstrom",
      cost: 2700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1565,
      name: "recipe_gungir",
      cost: 700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 1466,
      name: "gungir",
      cost: 6150,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 167,
      name: "recipe_desolator",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 168,
      name: "desolator",
      cost: 3500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 169,
      name: "recipe_yasha",
      cost: 600,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 170,
      name: "yasha",
      cost: 2050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 171,
      name: "recipe_mask_of_madness",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 172,
      name: "mask_of_madness",
      cost: 1775,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 173,
      name: "recipe_diffusal_blade",
      cost: 1050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 174,
      name: "diffusal_blade",
      cost: 2500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 175,
      name: "recipe_ethereal_blade",
      cost: 1100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 176,
      name: "ethereal_blade",
      cost: 4650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 177,
      name: "recipe_soul_ring",
      cost: 400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 178,
      name: "soul_ring",
      cost: 855,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 179,
      name: "recipe_arcane_boots",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 180,
      name: "arcane_boots",
      cost: 1300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 228,
      name: "recipe_octarine_core",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 235,
      name: "octarine_core",
      cost: 5275,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 181,
      name: "orb_of_venom",
      cost: 275,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 240,
      name: "blight_stone",
      cost: 300,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 640,
      name: "recipe_orb_of_corrosion",
      cost: 100,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 569,
      name: "orb_of_corrosion",
      cost: 925,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 599,
      name: "recipe_falcon_blade",
      cost: 250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 596,
      name: "falcon_blade",
      cost: 1125,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 597,
      name: "recipe_mage_slayer",
      cost: 400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 598,
      name: "mage_slayer",
      cost: 2400,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 184,
      name: "recipe_ancient_janggo",
      cost: 550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 185,
      name: "ancient_janggo",
      cost: 1700,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 930,
      name: "recipe_boots_of_bearing",
      cost: 1500,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 931,
      name: "boots_of_bearing",
      cost: 4125,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 186,
      name: "recipe_medallion_of_courage",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 187,
      name: "medallion_of_courage",
      cost: 1025,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 227,
      name: "recipe_solar_crest",
      cost: 900,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 229,
      name: "solar_crest",
      cost: 2625,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 188,
      name: "smoke_of_deceit",
      cost: 50,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 257,
      name: "tome_of_knowledge",
      cost: 75,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 189,
      name: "recipe_veil_of_discord",
      cost: 650,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 190,
      name: "veil_of_discord",
      cost: 1525,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 910,
      name: "recipe_revenants_brooch",
      cost: 800,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 911,
      name: "revenants_brooch",
      cost: 6200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 230,
      name: "recipe_guardian_greaves",
      cost: 1550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 231,
      name: "guardian_greaves",
      cost: 5050,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 205,
      name: "recipe_rod_of_atos",
      cost: 850,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 206,
      name: "rod_of_atos",
      cost: 2750,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 238,
      name: "recipe_iron_talon",
      cost: 1,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 239,
      name: "iron_talon",
      cost: 301,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 207,
      name: "recipe_abyssal_blade",
      cost: 1550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 208,
      name: "abyssal_blade",
      cost: 6250,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 209,
      name: "recipe_heavens_halberd",
      cost: 200,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 210,
      name: "heavens_halberd",
      cost: 3550,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 211,
      name: "recipe_ring_of_aquila",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 212,
      name: "ring_of_aquila",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 213,
      name: "recipe_tranquil_boots",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 214,
      name: "tranquil_boots",
      cost: 925,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 215,
      name: "shadow_amulet",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 253,
      name: "recipe_glimmer_cape",
      cost: 450,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 254,
      name: "glimmer_cape",
      cost: 1950,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1021,
      name: "river_painter",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1022,
      name: "river_painter2",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1023,
      name: "river_painter3",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1024,
      name: "river_painter4",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1025,
      name: "river_painter5",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1026,
      name: "river_painter6",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1027,
      name: "river_painter7",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1028,
      name: "mutation_tombstone",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1029,
      name: "super_blink",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1030,
      name: "pocket_tower",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1032,
      name: "pocket_roshan",
      cost: 1000,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 287,
      name: "keen_optic",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 288,
      name: "grove_bow",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 289,
      name: "quickening_charm",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 290,
      name: "philosophers_stone",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 291,
      name: "force_boots",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 292,
      name: "desolator_2",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 293,
      name: "phoenix_ash",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 294,
      name: "seer_stone",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 295,
      name: "greater_mango",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 302,
      name: "elixer",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 297,
      name: "vampire_fangs",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 829,
      name: "force_field",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 834,
      name: "black_powder_bag",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 849,
      name: "mechanical_arm",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 298,
      name: "craggy_coat",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 299,
      name: "greater_faerie_fire",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 300,
      name: "timeless_relic",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 301,
      name: "mirror_shield",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 303,
      name: "recipe_ironwood_tree",
      cost: 1,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 304,
      name: "ironwood_tree",
      cost: 151,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 328,
      name: "mango_tree",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 305,
      name: "royal_jelly",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 306,
      name: "pupils_gift",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 307,
      name: "tome_of_aghanim",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 308,
      name: "repair_kit",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 309,
      name: "mind_breaker",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 310,
      name: "third_eye",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 311,
      name: "spell_prism",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 325,
      name: "princes_knife",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 330,
      name: "witless_shako",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 334,
      name: "imp_claw",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 335,
      name: "flicker",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 336,
      name: "spy_gadget",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 326,
      name: "spider_legs",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 327,
      name: "helm_of_the_undying",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 329,
      name: "recipe_vambrace",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 331,
      name: "vambrace",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 312,
      name: "horizon",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 313,
      name: "fusion_rune",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 354,
      name: "ocean_heart",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 355,
      name: "broom_handle",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 356,
      name: "trusty_shovel",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 357,
      name: "nether_shawl",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 358,
      name: "dragon_scale",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 359,
      name: "essence_ring",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 360,
      name: "clumsy_net",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 361,
      name: "enchanted_quiver",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 362,
      name: "ninja_gear",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 363,
      name: "illusionsts_cape",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 364,
      name: "havoc_hammer",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 365,
      name: "panic_button",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 366,
      name: "apex",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 367,
      name: "ballista",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 368,
      name: "woodland_striders",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 275,
      name: "recipe_trident",
      cost: 1,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 370,
      name: "demonicon",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 317,
      name: "recipe_fallen_sky",
      cost: 1,
      secret_shop: 0,
      side_shop: 0,
      recipe: 1,
    },
    {
      id: 371,
      name: "fallen_sky",
      cost: 4751,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 372,
      name: "pirate_hat",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 373,
      name: "dimensional_doorway",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 374,
      name: "ex_machina",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 375,
      name: "faded_broach",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 376,
      name: "paladin_sword",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 377,
      name: "minotaur_horn",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 378,
      name: "orb_of_destruction",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 379,
      name: "the_leveller",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 349,
      name: "arcane_ring",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 381,
      name: "titan_sliver",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 565,
      name: "chipped_vest",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 566,
      name: "wizard_glass",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 570,
      name: "gloves_of_travel",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 573,
      name: "elven_tunic",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 574,
      name: "cloak_of_flames",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 575,
      name: "venom_gland",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 571,
      name: "trickster_cloak",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 576,
      name: "gladiator_helm",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 577,
      name: "possessed_mask",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 578,
      name: "ancient_perseverance",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 637,
      name: "star_mace",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 638,
      name: "penta_edged_sword",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 582,
      name: "oakheart",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 674,
      name: "warhammer",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 680,
      name: "bullwhip",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 675,
      name: "psychic_headband",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 676,
      name: "ceremonial_robe",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 686,
      name: "quicksilver_amulet",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 677,
      name: "book_of_shadows",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 678,
      name: "giants_ring",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 679,
      name: "vengeances_shadow",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 585,
      name: "stormcrafter",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 588,
      name: "overflowing_elixir",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 589,
      name: "mysterious_hat",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 824,
      name: "assassins_dagger",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 825,
      name: "ascetic_cap",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 826,
      name: "sample_picker",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 827,
      name: "icarus_wings",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 828,
      name: "misericorde",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 836,
      name: "light_robes",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 837,
      name: "heavy_blade",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 838,
      name: "unstable_wand",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 839,
      name: "fortitude_ring",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 840,
      name: "pogo_stick",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 835,
      name: "paintball",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 945,
      name: "seeds_of_serenity",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 946,
      name: "lance_of_pursuit",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 947,
      name: "occult_bracelet",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 948,
      name: "tome_of_omniscience",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 949,
      name: "ogre_seal_totem",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 940,
      name: "wand_of_the_brine",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 938,
      name: "slime_vial",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 939,
      name: "harpoon",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 950,
      name: "guardian_shell",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 968,
      name: "arcane_scout",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 969,
      name: "barricade",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 990,
      name: "eye_of_the_vizier",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 998,
      name: "manacles_of_power",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1000,
      name: "bottomless_chalice",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1017,
      name: "wand_of_sanctitude",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1076,
      name: "specialists_array",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
    {
      id: 1077,
      name: "dagger_of_ristul",
      cost: 0,
      secret_shop: 0,
      side_shop: 0,
      recipe: 0,
    },
  ];

  try {
    const [{ name }] = list.filter((x) => +x.id === +id);
    return name;
  } catch (error) {
    return id;
  }
};
